using Metro_Rail_DAL.Shared.Accounts.Transaction;
using System;
using System.Collections.Generic;
using System.Data;
namespace Metro_Rail_DAL.DAL.Accounts.Transaction
{
    public  class T13002DAL: CommonDAL
    {
        public DataTable GetVoucherList(string center, string fromDate, string toDate)
        {
            DataTable sql = new DataTable();
            var condition = "";
            if (center == "0") 
            { condition = $" (VERIFY_FLG IS NULL OR VERIFY_FLG='' )AND CONVERT(date, VOUCHER_DATE ,104) BETWEEN CONVERT(date, '{fromDate}' ,104) AND CONVERT(date, '{toDate}' ,104)";} 
           else { condition = $"(VERIFY_FLG IS NULL OR VERIFY_FLG='' ) AND T12005.CENTER_CODE='{center}' AND CONVERT(date, VOUCHER_DATE ,104) BETWEEN CONVERT(date, '{fromDate}' ,104) AND CONVERT(date, '{toDate}' ,104)";}

            // sql = Query($"SELECT ROW_NUMBER() OVER (ORDER BY  CAST(VOUCHER_NO as int) DESC) SL_NO, VOUCHER_NO, VOUCHER_DATE, T12005.CENTER_NAME, T12005.CENTER_CODE, T12006.VAUCHER_TYPE_NAME, T12006.VAUCHER_TYPE_CODE, T12007.TRANSACTION_TYPE_NAME, T12007.TRANSACTION_TYPE_CODE,T12007.TRANSACTION_TYPE_CODE, T12008.PARTY_TYPE_NAME,T12008.PARTY_TYPE_CODE, T12009.PARTY_NAME , T12009.PARTY_CODE,TOTAL_DEBIT,TOTAL_CREDIT, CASE  WHEN VERIFY_FLG IS NULL THEN '0' ELSE '1' END AS VERIFY_FLG FROM AT13001 JOIN T12005 ON AT13001.CENTER_CODE =T12005.CENTER_CODE JOIN T12006 ON AT13001.VAUCHER_TYPE_CODE =T12006.VAUCHER_TYPE_CODE JOIN T12007 ON AT13001.TRANSACTION_TYPE_CODE =T12007.TRANSACTION_TYPE_CODE JOIN T12008 ON AT13001.PARTY_TYPE_CODE =T12008.PARTY_TYPE_CODE JOIN T12009 ON AT13001.PARTY_CODE =T12009.PARTY_CODE WHERE VOUCHER_DATE BETWEEN CAST ('{fromDate}' AS DATE) AND CAST ('{toDate}' AS DATE) ORDER BY CAST(VOUCHER_NO as int) DESC");
            sql = Query($"SELECT ROW_NUMBER() OVER (ORDER BY  CAST(VOUCHER_NO as int) DESC) SL_NO, VOUCHER_NO, VOUCHER_DATE, T12005.CENTER_NAME, T12005.CENTER_CODE, T12006.VAUCHER_TYPE_NAME, T12006.VAUCHER_TYPE_CODE, T12007.TRANSACTION_TYPE_NAME, T12007.TRANSACTION_TYPE_CODE,T12007.TRANSACTION_TYPE_CODE, T12008.PARTY_TYPE_NAME,T12008.PARTY_TYPE_CODE, T12009.PARTY_NAME , T12009.PARTY_CODE,TOTAL_DEBIT,TOTAL_CREDIT, CASE  WHEN VERIFY_FLG IS NULL OR VERIFY_FLG='' THEN '0' ELSE '1' END AS VERIFY_FLG, AT13001.ENTRY_USER, T11020.T_USER_NAME FROM AT13001 JOIN T12005 ON AT13001.CENTER_CODE =T12005.CENTER_CODE JOIN T12006 ON AT13001.VAUCHER_TYPE_CODE =T12006.VAUCHER_TYPE_CODE JOIN T12007 ON AT13001.TRANSACTION_TYPE_CODE =T12007.TRANSACTION_TYPE_CODE JOIN T12008 ON AT13001.PARTY_TYPE_CODE =T12008.PARTY_TYPE_CODE JOIN T12009 ON AT13001.PARTY_CODE =T12009.PARTY_CODE JOIN T11020 ON AT13001.ENTRY_USER =T11020.T_USER_ID WHERE {condition} ORDER BY CAST(VOUCHER_NO as int) DESC");
            return sql;
        }

        public string VerifyedData(List<T13001Data> dataList, string user)
        {
            var sms = "";
            var date = DateTime.Now.ToString("dd-MM-yyyy");
            foreach (var i in dataList)
            {
                try
                {
                    Command($"UPDATE AT13001 SET VERIFY_FLG='{i.VERIFY_FLG}',VERIFY_DATE='{date}',VERIFY_USER='{user}' WHERE VOUCHER_NO='{i.VOUCHER_NO}'");
                    sms = "Saved successfully-1";
                }
                catch (Exception ex)
                {
                    sms = "Do not Save-0";
                }
                
            }
            return sms;
        }
    }
}
